### PR TITLE
Refactor package, separating byte calculations out

### PR DESCRIPTION
**Pull request by mkitti**
I have done a major refactoring of this package on the `total_refactor` branch: https://github.com/mkitti/ArrayAllocators.jl/tree/total_refactor

### CODE REVIEW

**Comment by mkitti** [comment]
@bjarthur and @carstenbauer , I would appreciate if you could review the refactored design.

**Comment by mkitti** [comment]
A documentation preview can be found here:
https://mkitti.github.io/ArrayAllocators.jl/previews/PR3/

**Comment by carstenbauer** [comment]
A few comments:
* On https://mkitti.github.io/ArrayAllocators.jl/previews/PR3/bytecalculators/, the index list mentions NUMA stuff but the actual functions aren't on that page (but in the NUMA section). Same issue [here](https://mkitti.github.io/ArrayAllocators.jl/previews/PR3/bytecalculators/)
* `numa` and `NumaAllocator` are not available. I get `UndefVarError` when I try to run the [examples](https://mkitti.github.io/ArrayAllocators.jl/previews/PR3/numa/#NumaArrayAllocators) in the docs. And `using NumaAllocators`, as written in the README.md, also doesn't work. How does that work? (And it should be documented.)
* `MemAlign` isn't mentioned in the docs? BTW, for testing that the alignment is actually correct, you can get inspiration [here](https://discourse.julialang.org/t/julia-alignas-is-there-a-way-to-specify-the-alignment-of-julia-objects-in-memory/57501/3?u=carstenbauer).
* IMO, you should cleanly separate examples from API references / interfaces, i.e. avoid a "everything on one page" layout like [here](https://mkitti.github.io/ArrayAllocators.jl/previews/PR3/). See https://documentation.divio.com/

**Comment by mkitti** [comment]
Thanks for the review @carstenbauer. Yes, I am primarily trying to improve the documentation now. I think part of the issue is that I need to move some of the docstrings outside of the operating system specific if statements.

> * `numa` and `NumaAllocator` are not available. I get `UndefVarError` when I try to run the [examples](https://mkitti.github.io/ArrayAllocators.jl/previews/PR3/numa/#NumaArrayAllocators) in the docs. And `using NumaAllocators`, as written in the README.md, also doesn't work. How does that work? (And it should be documented.)

Eventually, `using NumaAllocators` should work when I register the packages. For now, the following should work:
```
] activate --temp
] add https://github.com/mkitti/ArrayAllocators.jl#total_refactor
] add https://github.com/mkitti/ArrayAllocators.jl#total_refactor:NumaAllocators
] add https://github.com/mkitti/ArrayAllocators.jl#total_refactor:SafeByteCalculators
```

**Comment by mkitti** [comment]
@carstenbauer, what happens when `T`, the element type, is not a bitstype?

**Comment by carstenbauer** [comment]
> @carstenbauer, what happens when `T`, the element type, is not a bitstype?

For `MemAlign`? I would think that it just doesn't work / errors.

**Comment by mkitti** [comment]
We currently throw an error for `PosixMemAlign`. I'm wondering if we should throw an error more generally for other allocators other than `PosixMemAlign`.

**Comment by mkitti** [comment]
Thank you for the reviews, @carstenbauer and @bjarthur. I'm going to merge and release this now.

**Pull request merged**
